fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
heaven:
    resource: "@HeavenBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
